-- V1__criar_tabelas.sql

-- TABELA: FUNCIONARIO

CREATE TABLE funcionario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    setor VARCHAR(30) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    ramal VARCHAR(10) NOT NULL,
    criado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL
);


-- TABELA: TECNICO

CREATE TABLE tecnico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    especialidade VARCHAR(30) NOT NULL,
    ramal VARCHAR(10) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    criado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL
);


-- TABELA: CHAMADO

CREATE TABLE chamado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    descricao TEXT NOT NULL,
    prioridade VARCHAR(20) NOT NULL,
    categoria VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,

    funcionario_id BIGINT NOT NULL,
    tecnico_id BIGINT,

    data_abertura TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    data_conclusao TIMESTAMP WITHOUT TIME ZONE,

    solucao TEXT,

    criado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT fk_chamado_funcionario
        FOREIGN KEY (funcionario_id)
        REFERENCES funcionario(id),

    CONSTRAINT fk_chamado_tecnico
        FOREIGN KEY (tecnico_id)
        REFERENCES tecnico(id)
);